package:
  name: lib_sbpac
  version: "0.0.9"

source:
  path: ..

build:
  number: 0
  
requirements:
  build:
    - python
    - setuptools
  run:
    - python
   
about:
  home: https://github.com/KyunghanMin/StateBasedPredictionAndControl